### ISSUE TITLE
Fautes d'orthographe/de frappe

### ISSUE THREAD

**Issue by Aurelie-F** [WildCodeSchool/orleans-php-202009-project-coachsportif#335]
- "entrainement" au lieu de "entraînement" dans la navbar, dans la page Salle d'entrainement (titre et texte), dans la page Qui suis-je
- "Si vous-êtes intéressé" au lieu de "Si vous êtes intéressé" dans la page Salle d'entrainement et toutes les pages de services
- dans le formulaire de la page Contact, "Sujet de vôtre demande" au lieu de "Sujet de votre demande"
- "tarif" au lieu de "tarifs" dans le footer
- page Activité adaptée, "Une à 3 fois par semaine" : il faudrait écrire soit tout en lettres, soit tout en chiffres. Et l'espace dans "pendant 1h ," est placé avant la virgule au lieu d'après. "en vision" au lieu de "en visio"
- page Remise en forme, "et le sourire en fin de séance ..." : les 3 points devraient être collés à "séance". Il manque une majuscule à "loire"
- page Marche nordique, il manque une majuscule à "alors RDV tous [...]". Il manque un point pour les points de suspension après "chemins". "qui vous redonnent du souffle" au lieu de "qui vous redonne du souffle"
- page Santé en entreprise, il manque une majuscule à "c'est probablement". "c'est probablement du à" au lieu de "c'est probablement dû à". Il manque un point entre "quotidien"  et "Un mot d'ordre"
- page Salle d'entrainement, un point en trop après "efforts !". Il manque un espace dans "mais il ya du bon matériel" entre "y" et "a". Un "s" en trop dans "petits matériel"
- page Qui suis-je, "professionnels. J'ai eu envie" au lieu de "professionnels, j'ai eu envie". Majuscule en trop à "Accompagner". Il manque un point entre "qualité de vie" et "Je mets". "charge de la santé. Participer" au lieu de "charge de la santé, participer"
- page de nouveau compte, un ":" en trop après "Accepter les termes et conditions"

**Comment by JulieRebeyrolle** [comment]
Admin - Media "Lien You_tube" > "YouTube
